baseURL = "https://blog.yulin.ltd/"
languageCode = "zh-cn"
title = "雨林说"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  disableSpecial1stPost = true
  author = "Yulin"
