baseURL = "https://blog.yulin.ltd/"
languageCode = "zh-cn"
title = "雨林说"
theme = "PaperMod"


[params]
  
  [params.homeInfoParams]
    Title = "Hi there."
    Content = "Can be Info, links, about..."
  
  ShowReadingTime = true
  ShowShareButtons = false
  disableSpecial1stPost = true
  author = "雨林"
  defaultTheme = "auto"
  description = "This is a blog of mine." 
  ShowBreadCrumbs = true


